FROM node:18-alpine AS builder

WORKDIR /app

COPY ../frontend/package.json ../frontend/package-lock.json ./

RUN npm install --production
COPY ../frontend .

RUN npm run build

# Multi-stage build
FROM node:18-alpine

WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3000

CMD ["npm", "run", "start"]
